### ISSUE TITLE
部署到Google Colab的移植版脚本

### ISSUE THREAD

**Issue by Sparklewink** [xming521/WeClone#105]
Google Colab提供的T4免费GPU，可以满足训练需求，花了一些时间把训练命令写到Google Colab上了，欢迎大佬们来改进！
笔记地址：https://colab.research.google.com/drive/1od_9FfdozlOL0Ujw7zpQzdvr5wxWLbrd?usp=drive_link

**Comment by xming521** [comment]
T4的bug解决了？

**Comment by thomas-art** [comment]
ERROR: Package 'weclone' requires a different Python: 3.11.11 not in '<3.11,>=3.10'

**Comment by daxiaolaogui** [comment]
> ERROR: Package 'weclone' requires a different Python: 3.11.11 not in '<3.11,>=3.10'

降级版本到3.10

**Comment by thomas-art** [comment]
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 260.00 MiB. GPU 0 has a total capacity of 14.74 GiB of which 18.12 MiB is free. Process 75425 has 14.72 GiB memory in use. Of the allocated memory 14.46 GiB is allocated by PyTorch, and 136.96 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by thomas-art** [comment]
还是得上L4，不然爆显存
