### ISSUE TITLE
8B模型可以微调，但数据清洗时爆显存

### ISSUE THREAD

**Issue by clostou** [xming521/WeClone#108]
全部默认设置，A6000单卡训练，微调时显存占用32GiB，推理时占用15.3GiB，但数据预处理时如果把打分打开，会直接爆显存（>48GiB）

```
(.venv) (base) [zhuofeng@server WeClone]$ weclone-cli make-dataset
[WeClone] I | 19:56:18 | Loading configuration from: ./settings.jsonc
[WeClone] I | 19:56:18 | 聊天记录禁用词: ['地址', '密码', '账号']
[WeClone] I | 19:56:18 | 共发现 6 个 CSV 文件，开始处理
[WeClone] W | 19:56:18 | 组合后消息长度超过256将截断：
... ... 
INFO 05-20 19:56:19 [__init__.py:239] Automatically detected platform cuda.
[WeClone] I | 19:56:20 | 开始使用llm对数据打分
[INFO|configuration_utils.py:697] 2025-05-20 19:56:20,940 >> loading configuration file ./Qwen2.5-7B-Ins                                                                                      truct/config.json
[INFO|configuration_utils.py:771] 2025-05-20 19:56:20,941 >> Model config Qwen2Config {
  "_name_or_path": "./Qwen2.5-7B-Instruct",
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 3584,
  "initializer_range": 0.02,
  "intermediate_size": 18944,
  "max_position_embeddings": 32768,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 28,
  "num_hidden_layers": 28,
  "num_key_value_heads": 4,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": 131072,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.49.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 152064
}

[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:20,949 >> loading file vocab.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:20,949 >> loading file merges.txt
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:20,949 >> loading file tokenizer.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:20,950 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:20,950 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:20,950 >> loading file tokenizer_config.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:20,950 >> loading file chat_template.jinja
[INFO|tokenization_utils_base.py:2313] 2025-05-20 19:56:21,311 >> Special tokens have been added in the                                                                                       vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[INFO|configuration_utils.py:697] 2025-05-20 19:56:21,312 >> loading configuration file ./Qwen2.5-7B-Ins                                                                                      truct/config.json
[INFO|configuration_utils.py:771] 2025-05-20 19:56:21,312 >> Model config Qwen2Config {
  "_name_or_path": "./Qwen2.5-7B-Instruct",
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 3584,
  "initializer_range": 0.02,
  "intermediate_size": 18944,
  "max_position_embeddings": 32768,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 28,
  "num_hidden_layers": 28,
  "num_key_value_heads": 4,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": 131072,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.49.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 152064
}

[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:21,313 >> loading file vocab.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:21,313 >> loading file merges.txt
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:21,313 >> loading file tokenizer.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:21,313 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:21,313 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:21,313 >> loading file tokenizer_config.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:21,313 >> loading file chat_template.jinja
[INFO|tokenization_utils_base.py:2313] 2025-05-20 19:56:21,665 >> Special tokens have been added in the                                                                                       vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[INFO|2025-05-20 19:56:21] llamafactory.data.template:157 >> Add <|im_end|> to stop words.
[INFO|configuration_utils.py:697] 2025-05-20 19:56:21,705 >> loading configuration file ./Qwen2.5-7B-Ins                                                                                      truct/config.json
[INFO|configuration_utils.py:697] 2025-05-20 19:56:21,705 >> loading configuration file ./Qwen2.5-7B-Ins                                                                                      truct/config.json
[INFO|configuration_utils.py:771] 2025-05-20 19:56:21,705 >> Model config Qwen2Config {
  "_name_or_path": "./Qwen2.5-7B-Instruct",
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 3584,
  "initializer_range": 0.02,
  "intermediate_size": 18944,
  "max_position_embeddings": 32768,
  "max_window_layers": 28,
  "model_type": "qwen2",
  "num_attention_heads": 28,
  "num_hidden_layers": 28,
  "num_key_value_heads": 4,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": 131072,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.49.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 152064
}

[INFO|image_processing_auto.py:301] 2025-05-20 19:56:21,707 >> Could not locate the image processor conf                                                                                      iguration file, will try to use the model config instead.
INFO 05-20 19:56:29 [config.py:585] This model supports multiple tasks: {'reward', 'embed', 'classify',                                                                                       'generate', 'score'}. Defaulting to 'generate'.
INFO 05-20 19:56:29 [config.py:1697] Chunked prefill is enabled with max_num_batched_tokens=8192.
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:30,929 >> loading file vocab.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:30,930 >> loading file merges.txt
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:30,930 >> loading file tokenizer.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:30,930 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:30,930 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:30,930 >> loading file tokenizer_config.json
[INFO|tokenization_utils_base.py:2048] 2025-05-20 19:56:30,930 >> loading file chat_template.jinja
[INFO|tokenization_utils_base.py:2313] 2025-05-20 19:56:31,274 >> Special tokens have been added in the                                                                                       vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[INFO|configuration_utils.py:1093] 2025-05-20 19:56:31,376 >> loading configuration file ./Qwen2.5-7B-In                                                                                      struct/generation_config.json
[INFO|configuration_utils.py:1140] 2025-05-20 19:56:31,377 >> Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.05,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

WARNING 05-20 19:56:31 [utils.py:2181] We must use the `spawn` multiprocessing start method. Overriding                                                                                       VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/getting_started/troubleshoot                                                                                      ing.html#python-multiprocessing for more information. Reason: CUDA is initialized
INFO 05-20 19:56:35 [__init__.py:239] Automatically detected platform cuda.
INFO 05-20 19:56:37 [core.py:54] Initializing a V1 LLM engine (v0.8.2) with config: model='./Qwen2.5-7B-                                                                                      Instruct', speculative_config=None, tokenizer='./Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokeni                                                                                      zer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=Tr                                                                                      ue, dtype=torch.bfloat16, max_seq_len=3072, download_dir=None, load_format=auto, tensor_parallel_size=1,                                                                                       pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_c                                                                                      ache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar',                                                                                       reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_trace                                                                                      s_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_                                                                                      model_name=./Qwen2.5-7B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_c                                                                                      aching=True, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=Fal                                                                                      se, mm_processor_kwargs=None, pooler_config=None, compilation_config={"level":3,"custom_ops":["none"],"s                                                                                      plitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compi                                                                                      le_sizes":[],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,48                                                                                      8,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,28                                                                                      0,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64                                                                                      ,56,48,40,32,24,16,8,4,2,1],"max_capture_size":512}
WARNING 05-20 19:56:37 [utils.py:2321] Methods determine_num_available_blocks,device_config,get_cache_bl                                                                                      ock_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x1528a4a                                                                                      76fb0>
INFO 05-20 19:56:43 [parallel_state.py:954] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0,                                                                                       TP rank 0
INFO 05-20 19:56:43 [cuda.py:220] Using Flash Attention backend on V1 engine.
INFO 05-20 19:56:43 [gpu_model_runner.py:1174] Starting to load model ./Qwen2.5-7B-Instruct...
WARNING 05-20 19:56:43 [topk_topp_sampler.py:63] FlashInfer is not available. Falling back to the PyTorc                                                                                      h-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.44it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.31it/s]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.27it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:03<00:00,  1.25it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:03<00:00,  1.27it/s]

INFO 05-20 19:56:46 [loader.py:447] Loading weights took 3.20 seconds
INFO 05-20 19:56:47 [gpu_model_runner.py:1186] Model loading took 14.2487 GB and 3.397916 seconds
INFO 05-20 19:56:53 [backends.py:415] Using cache directory: /home/zhuofeng/.cache/vllm/torch_compile_ca                                                                                      che/441c2166f8/rank_0_0 for vLLM's torch.compile
INFO 05-20 19:56:53 [backends.py:425] Dynamo bytecode transform time: 5.83 s
INFO 05-20 19:56:53 [backends.py:115] Directly load the compiled graph for shape None from the cache
INFO 05-20 19:56:58 [monitor.py:33] torch.compile takes 5.83 s in total
INFO 05-20 19:57:00 [kv_cache_utils.py:566] GPU KV cache size: 464,304 tokens
INFO 05-20 19:57:00 [kv_cache_utils.py:569] Maximum concurrency for 3,072 tokens per request: 151.14x
INFO 05-20 19:57:34 [gpu_model_runner.py:1534] Graph capturing finished in 35 secs, took 1.46 GiB
INFO 05-20 19:57:35 [core.py:151] init engine (profile, create kv cache, warmup model) took 47.84 second                                                                                      s
/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py:2059: UserWar                                                                                      ning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Processed prompts:   0%|   | 0/4098 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]                                                                                      ERROR 05-20 19:58:04 [core.py:343] EngineCore hit an exception: Traceback (most recent call last):
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/v1/engine/core.py", line 336, in run_engine_core
ERROR 05-20 19:58:04 [core.py:343]     engine_core.run_busy_loop()
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/v1/engine/core.py", line 370, in run_busy_loop
ERROR 05-20 19:58:04 [core.py:343]     outputs = step_fn()
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/v1/engine/core.py", line 195, in step
ERROR 05-20 19:58:04 [core.py:343]     output = self.model_executor.execute_model(scheduler_output)
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/v1/executor/abstract.py", line 77, in execute_model
ERROR 05-20 19:58:04 [core.py:343]     output = self.collective_rpc("execute_model",
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/executor/uniproc_executor.py", line 56, in collective_rpc
ERROR 05-20 19:58:04 [core.py:343]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/utils.py", line 2255, in run_method
ERROR 05-20 19:58:04 [core.py:343]     return func(*args, **kwargs)
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 05-20 19:58:04 [core.py:343]     return func(*args, **kwargs)
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/v1/worker/gpu_worker.py", line 242, in execute_model
ERROR 05-20 19:58:04 [core.py:343]     output = self.model_runner.execute_model(scheduler_output)
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 05-20 19:58:04 [core.py:343]     return func(*args, **kwargs)
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/v1/worker/gpu_model_runner.py", line 1057, in execute_model
ERROR 05-20 19:58:04 [core.py:343]     sampler_output = self.model.sample(
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/model_executor/models/qwen2.py", line 480, in sample
ERROR 05-20 19:58:04 [core.py:343]     next_tokens = self.sampler(logits, sampling_metadata)
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
ERROR 05-20 19:58:04 [core.py:343]     return self._call_impl(*args, **kwargs)
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /torch/nn/modules/module.py", line 1750, in _call_impl
ERROR 05-20 19:58:04 [core.py:343]     return forward_call(*args, **kwargs)
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/v1/sample/sampler.py", line 47, in forward
ERROR 05-20 19:58:04 [core.py:343]     logits = self.apply_penalties(logits, sampling_metadata)
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/v1/sample/sampler.py", line 187, in apply_penalties
ERROR 05-20 19:58:04 [core.py:343]     logits = apply_all_penalties(
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/v1/sample/ops/penalties.py", line 39, in apply_all_penalties
ERROR 05-20 19:58:04 [core.py:343]     return apply_penalties(logits, prompt_token_ids, output_tokens_t,
ERROR 05-20 19:58:04 [core.py:343]   File "/home/zhuofeng/lgq/WeClone/.venv/lib/python3.10/site-packages                                                                                      /vllm/model_executor/layers/utils.py", line 52, in apply_penalties
ERROR 05-20 19:58:04 [core.py:343]     logits[logits <= 0] *= torch.where(prompt_mask | output_mask,
ERROR 05-20 19:58:04 [core.py:343] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.63 Gi                                                                                      B. GPU 0 has a total capacity of 47.54 GiB of which 395.50 MiB is free. Including non-PyTorch memory, th                                                                                      is process has 46.97 GiB memory in use. Of the allocated memory 43.16 GiB is allocated by PyTorch, with                                                                                       97.50 MiB allocated in private pools (e.g., CUDA Graphs), and 2.16 GiB is reserved by PyTorch but unallo                                                                                      cated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segmen                                                                                      ts:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stab                                                                                      le/notes/cuda.html#environment-variables)
ERROR 05-20 19:58:04 [core.py:343]
CRITICAL 05-20 19:58:04 [core_client.py:269] Got fatal signal from worker processes, shutting down. See                                                                                       stack trace above for root cause issue.
已杀死
```

**Comment by hoooooli** [comment]
请问你解决这个问题了吗？

**Comment by hoooooli** [comment]
"/home/test001/zzw/WeClone/weclone/core/inference/offline_infer.py"
修改"gpu_memory_utilization": 0.8,改低点减少缓存，还可以修改"tensor_parallel_size":支持多卡，但是只能是偶数。
engine_args = {
        "model": model_args.model_name_or_path,
        "trust_remote_code": True,
        "dtype": model_args.infer_dtype,
        "max_model_len": cutoff_len + max_new_tokens,
        "tensor_parallel_size":  2,
        # "pipeline_parallel_size": pipeline_parallel_size,
        # "data_parallel_size": get_device_count(), // vllm0.8.5版本支持DP
        "disable_log_stats": True,
        "enable_lora": model_args.adapter_name_or_path is not None,
        "enable_prefix_caching": True,  # 是否启用前缀缓存
        "gpu_memory_utilization": 0.8,
        # "quantization": "bitsandbytes", # 是否启用vllm的 bitsandbytes 的量化加载
        # "load_format": "bitsandbytes",
    }

**Comment by clostou** [comment]
> "/home/test001/zzw/WeClone/weclone/core/inference/offline_infer.py" 修改"gpu_memory_utilization": 0.8,改低点减少缓存。 engine_args = { "model": model_args.model_name_or_path, "trust_remote_code": True, "dtype": model_args.infer_dtype, "max_model_len": cutoff_len + max_new_tokens, #"tensor_parallel_size": 1, # "pipeline_parallel_size": pipeline_parallel_size, # "data_parallel_size": get_device_count(), // vllm0.8.5版本支持DP "disable_log_stats": True, "enable_lora": model_args.adapter_name_or_path is not None, "enable_prefix_caching": True, # 是否启用前缀缓存 "gpu_memory_utilization": 0.8, # "quantization": "bitsandbytes", # 是否启用vllm的 bitsandbytes 的量化加载 # "load_format": "bitsandbytes", }

感谢，`gpu_memory_utilization`从默认的0.95改成0.8后问题解决，打分过程中的峰值显存占用大概在46GiB左右
